// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Toaster } from "sonner";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MindsetFit - Seu Personal Trainer Digital",
  description: "Planejamento nutricional e treinos personalizados",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        {/* viewport para mobile */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full bg-black text-white flex flex-col items-center`}
      >
        {/* container centralizado com cara de app mobile */}
        <main className="w-full max-w-[480px] px-4 py-4">
          {children}
        </main>

        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
